import Head from "next/head";
import { Box } from "@mui/system";
import { Typography } from "@mui/material";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Stories from "../components/Stories";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        style={{
          marginLeft: "5%",
          marginRight: "5%",
        }}
      >
        <Box
          style={{
            maxWidth: "100%",
            backgroundColor: "whitesmoke",
            padding: "5px",
          }}
        >
          <Header />
          {/* <Stories /> */}
        </Box>
      </Box>
    </div>
  );
}
