import Head from "next/head";
import { Box } from "@mui/system";
import styles from "../styles/Home.module.css";
import NewsRetrieve from "../components/NewsRetrieve";
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter";
import { IconButton, Typography } from "@mui/material";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>NewzWorthy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        style={{
          display: "flex",
        }}
      >
        {/* <Box>
          <IconButton
            onClick={() => router.replace("https://tommyj.net/portfolio")}
          >
            <BusinessCenterIcon></BusinessCenterIcon>
          </IconButton>
          <Typography style={{ fontSize: "10px" }}>TommyJ</Typography>
          <Typography style={{ fontSize: "10px" }}>Portfolio</Typography>
        </Box> */}

        <Box
          style={{
            maxWidth: "100%",
            backgroundColor: "whitesmoke",
            padding: "5px",
          }}
        >
          <NewsRetrieve />
        </Box>
      </Box>
    </div>
  );
}
